### PR TITLE
Fix circular reference by using generic i.o. Json

### PR DESCRIPTION
**Pull request by chribsen**
Can't build a circular ref:
```
node_modules/@connectedcars/test/build/dist/common.d.ts:2:21 - error TS2456: Type alias 'Json' circularly references itself.

2 export declare type Json = null | boolean | number | string | Json[] | {
                      ~~~~


Found 1 error.
```

### CODE REVIEW

**Comment by tlbdk** [comment]
Sounds like you are using an old typescript?

**Comment by tlbdk** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#more-recursive-type-aliases

**Comment by tlbdk** [comment]
I think it's fine to make it generic but let's keep Json as the default <T = Json>

**Comment by chribsen** [comment]
> Sounds like you are using an old typescript?

Yes, that was the issue

**Pull request closed without merging**
